### ISSUE TITLE
Dependensi pada level usecase

### ISSUE THREAD

**Issue by faishaldev** [arasopraza/NestJS-Starter-Template#1]
Halo mas @arasopraza, sebelumnya terima kasih atas panduannya untuk penerapan clean architecture pada aplikasi back end menggunakan Nest JS, saya sangat tercerahkan dengan adanya tutorial yang dijelaskan oleh mas @arasopraza melalui artikelnya pada platform Medium.

Disini, saya memposisikan sebagai pemula yang pernah membuat aplikasi backend dengan menggunakan teknologi lain dengan menggunakan JavaScript dan mencoba untuk menggunakan TypeScript dan Nest JS untuk membuat aplikasi backend.

Ketika saya mencoba mengikuti, saya merasa ada yang ingin ditanyakan pada level use case, saya melihat pemanggilan dependensi keluar ke infrastruktur, apakah hal tersebut yang mas @arasopraza pandukan itu wajar? Atau apakah sebenarnya hal tersebut melanggar dari konsep yang dijelaskan oleh Uncle Bob atau pengecualian yah untuk Nest JS? Mohon bimbingannya🙏

**Comment by arasopraza** [comment]
Halo Mas @musshal, sebelumnya saya mengucapkan terima kasih atas masukan atau pertanyaannya. Saya senang sekali ketika mengetahui bahwa tulisan saya memberikan manfaat ke orang lain terutama ke Mas @musshal. Izin saya menjawab pertanyaannya.Pemanggilan dependensi keluar yaitu ke infrastruktur melanggar konsep dari clean architecture yang dijelaskan oleh Uncle Bob. Seharusnya di use case hanya boleh memanggil dependensi ke dalam yaitu ke Domain. Di kode yang salah tulis itu merupakan kesalahan dari saya. Seharusnya saya memanggil repository yang ada di domain bukan yang ada di infrastruktur. Jadi untuk kodenya sudah saya update ya. Terima kasih banyak.
